### ISSUE TITLE
bug: out of memory

### ISSUE THREAD

**Issue by trim21** [GongT/baobao#2]
I'm trying to use it to append js extension and got a v8 error says can't alloc

```text
❯❯ ~\..\bangumi-episode-calendar git:(bug-out-of-memory) npx ttsc
>>> plugin: @build-script/typescript-transformer-dual-package <<<
>>> plugin: @build-script/typescript-transformer-dual-package <<<
>>> plugin: @build-script/typescript-transformer-dual-package <<<

<--- Last few GCs --->

[51816:000001087CA30350]    53022 ms: Scavenge 4029.5 (4107.8) -> 4028.8 (4130.1) MB, 7.6 / 0.0 ms  (average mu = 0.929, current mu = 0.712) allocation failure;
[51816:000001087CA30350]    53801 ms: Mark-sweep 4043.5 (4130.1) -> 4041.3 (4145.6) MB, 617.5 / 0.0 ms  (average mu = 0.822, current mu = 0.389) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7ACCF1B7F node_api_throw_syntax_error+203775
...
```

you can find reproduce repo here:

https://github.com/trim21/bug-reproduce-1/actions/runs/3555054029/jobs/5971524480

**Comment by trim21** [comment]
And in fact, I'm only trying to append file extension, and https://www.npmjs.com/package/@build-script/typescript-transformer-append-js-extension says I should use `@build-script/typescript-transformer-dual-package` how can I only go that ? I didn't need dual package at all.

**Comment by GongT** [comment]
@trim21 很神奇，我在本地用相同版本很顺利的过了，CI上就不行。。可能遇到什么很边缘的bug了。。毕竟我这些东西都是纯js，死循环也不会弄崩溃才对。

append-js不维护主要是功能被dual-package完全覆盖了，之后可能考虑加一个选项（？）     
我现在不用ttypescript改用heft了，所以一直懒得加（     
现在可以先把 *.cjs 和 *.cjs.map 忽略（

**Comment by trim21** [comment]
node版本也相同吗？我现在用的是18

**Comment by trim21** [comment]
可能是死循环并且一直在创建被引用的变量吧，因为最后的报错是内存耗尽…

**Comment by GongT** [comment]
node也相同

**Comment by GongT** [comment]
[doge]彻底改成heft插件了
